version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: pixelz
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sports-betting
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/data/init-data.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_SERVER: postgres
      PGADMIN_DEFAULT_SERVER_HOST: postgres
      PGADMIN_DEFAULT_SERVER_PORT: 5432
      PGADMIN_DEFAULT_SERVER_USERNAME: pixelz
      PGADMIN_DEFAULT_SERVER_PASSWORD: password
    ports:
      - "5050:5050"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:8080"

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - "5000:5000"

volumes:
  postgres_data:
