name: Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  

jobs:

  build-front:
    name: Build frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          cd frontend
          docker buildx build -t betting-app-front:latest .
          docker save betting-app-front:latest > betting-app-front.tar

      # - name: Login to Registry
      #   run: echo "${{ env.TOKEN }}" | docker login "${{ env.REGISTRY_URL }}" -u "${{ env.REGISTRY_USER }}" --password-stdin

      # - name: Push to Registry
      #   run: docker push "${{ env.REGISTRY_URL }}"/dam-front:latest


  build-back:
    name: Build backend
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build Docker Image
        run: |
          cd backend
          docker buildx build -t betting-app-back:latest .
          docker save betting-app-back:latest > betting-app-back.tar

      # - name: Login to Registry
      #   run: echo "${{ env.TOKEN }}" | docker login "${{ env.REGISTRY_URL }}" -u "${{ env.REGISTRY_USER }}" --password-stdin

      # - name: Push to Registry
      #   run: docker push "${{ env.REGISTRY_URL }}"/dam-api:latest

  trivy-scan:
      name: Trivy Container Scan
      runs-on: ubuntu-latest
      needs: [build-front, build-back]

      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Load Docker Images
          run: |
            docker load -i frontend/betting-app-front.tar
            docker load -i backend/betting-app-back.tar
        
        - name: Trivy Scan
          uses: aquasecurity/trivy-action@0.20.0
          with:
            image-ref: ${{ matrix.image }}
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'
          strategy:
            matrix:
              image: ['betting-app-front:latest', 'betting-app-back:latest']